title: AFK
author: Zapo
email: email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A Jekyll site with Github pages

# social links
twitter_username: @zapo__
github_username:  z4p0

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
